# This is a basic workflow to help you get started with Actions

name: o+Okteto Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Okteto Pipeline
        uses: okteto/pipeline@latest
        with:
          # The name of the pipeline
          name: contacts-fis2021
          # If present, the namespace scope for this action. If not specified, it will use the current context
          namespace: fis



